//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lotrinh()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public string malotrinh { get; set; }
        public string maxe { get; set; }
        public string matuyen { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<decimal> gia { get; set; }
    
        public virtual Tuyen Tuyen { get; set; }
        public virtual Xe Xe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
