//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeXe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using VeXe.Models;

    public partial class vexeEntities : DbContext
    {
        public vexeEntities()
            : base("name=vexeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Lotrinh> Lotrinhs { get; set; }
        public virtual DbSet<Tuyen> Tuyens { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    }
}
