//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuyen()
        {
            this.Lotrinhs = new HashSet<Lotrinh>();
        }
    
        public string matuyen { get; set; }
        public string noibatdau { get; set; }
        public string noiketthuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lotrinh> Lotrinhs { get; set; }
    }
}
