//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public string mave { get; set; }
        public string maghe { get; set; }
        public string malotrinh { get; set; }
        public string makh { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual Lotrinh Lotrinh { get; set; }
    }
}
